#!/usr/bin/env php
<?php

use Cumulus\Cumulus\Commands;
use Dotenv\Dotenv;
use Dotenv\Repository\Adapter\EnvConstAdapter as V4orV5EnvConstAdapter;
use Dotenv\Repository\Adapter\ServerConstAdapter as V4orV5ServerConstAdapter;
use Dotenv\Repository\RepositoryBuilder;
use Laravel\VaporCli\Application;
use Illuminate\Container\Container;

/**
 * Require the autoloader.
 */
if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Load the environment variables.
 */
(function () {
    if (class_exists(RepositoryBuilder::class)) {
        $adapters = [
            V4orV5EnvConstAdapter::class,
            V4orV5ServerConstAdapter::class,
        ];

        if (method_exists(RepositoryBuilder::class, 'addReader')) { // V5
            $repository = RepositoryBuilder::createWithNoAdapters();

            foreach ($adapters as $adapter) {
                $repository = $repository
                    ->addReader($adapter)
                    ->addWriter($adapter);
            }
        } else { // V4
            $adapters = array_map(function ($adapterClass) {
                return new $adapterClass();
            }, $adapters);

            $repository = RepositoryBuilder::create()
                ->withReaders($adapters)
                ->withWriters($adapters);
        }

        Dotenv::create(
            $repository->immutable()->make(),
            __DIR__
        )->safeLoad();
    }
})();

/**
 * Create the container instance.
 */
Container::setInstance($container = new Container());

/**
 * Start the console application.
 */
$app = new Application('Cumulus', '0.1.0');

// Authentication...
$app->add(new Commands\CloudflareLoginCommand());
$app->add(new Commands\CloudflareLogoutCommand());

// Records...
$app->add(new Commands\RecordsImportCommand());

$app->run();
